### ISSUE TITLE
Fix home and doc urls

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/bintrees-feedstock#1]
As noted at `staged-recipes`, the [`home` is incorrect]( https://github.com/conda-forge/staged-recipes/pull/4455#pullrequestreview-77834288 ) and the [`doc_url` is incorrect]( https://github.com/conda-forge/staged-recipes/pull/4455#pullrequestreview-77834985 ). Both need to be updated to point to the repo instead and the recipe needs to be re-rendered after these changes.

**Comment by pvanheus** [comment]
Updated the meta.yml to point to the PyPi page in  #12. While the github repository is the home for development, it is not up to date in terms of releases, whereas the PyPi page is.

**Comment by jakirkham** [comment]
Thanks! 😄
